[project]
name = "fast-retic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pyyaml>=6.0.2",
    "tzlocal>=5.3.1",
]
